# Generated by Django 2.2.3 on 2019-09-08 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0002_auto_20190908_0330'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Teacher',
        ),
    ]
