# Generated by Django 2.2.3 on 2019-09-08 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0003_auto_20190908_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reg.Institute'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='institute',
            field=models.ManyToManyField(to='reg.Institute'),
        ),
    ]
